# Generated by Django 6.0.5 on 2026-08-06 13:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_proyecto_trabajador_avanceobra'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(default='OptiObra S.A.S.', max_length=200)),
                ('nit_runc', models.CharField(default='900.000.000-1', max_length=50)),
                ('direccion', models.CharField(default='Calle Principal #123', max_length=255)),
                ('telefono', models.CharField(default='+57 300 000 0000', max_length=50)),
                ('email_contacto', models.EmailField(default='contacto@optiobra.local', max_length=254)),
                ('moneda_principal', models.CharField(default='COP', max_length=10)),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Configuraciones de Empresa',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alerta_stock_minimo_defecto', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('dias_notificacion_vencimiento', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)])),
                ('modo_mantenimiento', models.BooleanField(default=False)),
                ('formato_fecha', models.CharField(choices=[('YYYY-MM-DD', 'YYYY-MM-DD'), ('DD/MM/YYYY', 'DD/MM/YYYY'), ('MM/DD/YYYY', 'MM/DD/YYYY')], default='YYYY-MM-DD', max_length=20)),
                ('notificaciones_email', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Configuraciones del Sistema',
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Perfiles de Usuario',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo_reporte', models.CharField(choices=[('inventario', 'Inventario General'), ('stock_bajo', 'Materiales con Stock Bajo'), ('proyectos_avances', 'Avances de Proyectos'), ('costos_inventario', 'Costos e Valorización'), ('trabajadores', 'Personal y Trabajadores')], max_length=50)),
                ('formato', models.CharField(choices=[('json', 'JSON'), ('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], default='json', max_length=20)),
                ('parametros', models.JSONField(blank=True, null=True)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('completado', 'Completado'), ('error', 'Error')], default='completado', max_length=20)),
                ('resumen_datos', models.JSONField(blank=True, null=True)),
                ('solicitado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_solicitados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reportes Generados',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
