# Generated by Django 6.0.5 on 2026-08-13 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_proyecto_avance_proyecto_creado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='avatar_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
