# Generated by Django 6.0.5 on 2026-08-27 19:32

from django.db import migrations


def recalcular_avances(apps, schema_editor):
    """Recalcula el avance de todos los proyectos a partir de sus tareas."""
    Proyecto = apps.get_model('api', 'Proyecto')
    Tarea = apps.get_model('api', 'Tarea')

    for proyecto in Proyecto.objects.all():
        total = Tarea.objects.filter(proyecto_id=proyecto.id).count()
        completadas = Tarea.objects.filter(
            proyecto_id=proyecto.id, estado='completada'
        ).count()
        avance = round((completadas / total) * 100) if total > 0 else 0
        proyecto.avance = avance
        proyecto.porcentaje_avance = avance
        proyecto.save(update_fields=['avance', 'porcentaje_avance'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_tarea_trabajador_asignado_perfilusuario_dni_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AvanceObra',
        ),
        migrations.RunPython(recalcular_avances, migrations.RunPython.noop),
    ]