# Generated by Django 6.0.5 on 2026-08-27 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_conversacionia_mensajeia'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacionia',
            name='materiales_sugeridos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
